apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: client-kube
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
          - name: REACT_APP_SERVER_IP
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: REACT_APP_SERVER_IP
